
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - db.k8s.io
  resources:
  - cassandraclusters
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - db.k8s.io
  resources:
  - cassandraclusters/status
  verbs:
  - get
  - update
  - patch
